version: "3"
services:
  bot:
    restart: always
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      PREFIX: ${PREFIX}
      BOT_ID: ${BOT_ID}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      YOUTUBE_DATA_API_KEY: ${YOUTUBE_DATA_API_KEY}
    volumes:
      - .:/app
    working_dir: "/app"
    tty: true